"""Writes the public demo's policy: the default policy plus the trained injection classifier
(when one exists) and a per-visitor rate limit that keeps the free instance responsive."""

import argparse

import yaml

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source")
parser.add_argument("out")
parser.add_argument("--injection-threshold", type=float)
args = parser.parse_args()

with open(args.source) as f:
    policy = yaml.safe_load(f)
if args.injection_threshold is not None:
    policy["input_rails"]["injection"] = {
        "model": "models/injection-onnx",
        "threshold": args.injection_threshold,
        "max_windows": 4,
    }
policy["rate_limit"] = {"requests": 30, "per_seconds": 60}
with open(args.out, "w") as f:
    f.write("# Generated by deploy/demo_policy.py from policies/default.yaml.\n")
    yaml.safe_dump(policy, f, sort_keys=False)
