"""Writes a policy for a deployment or benchmark: the default policy plus trained models and
deployment-specific settings.

    python deploy/make_policy.py policies/default.yaml out.yaml \\
        --injection-model models/injection-onnx --injection-threshold 0.97 \\
        --toxicity-model models/toxicity-onnx --rate-limit 30 --on-block refuse
"""

import argparse

import yaml

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source")
parser.add_argument("out")
parser.add_argument("--injection-model", default="models/injection-onnx")
parser.add_argument("--injection-threshold", type=float, help="Add the injection rail")
parser.add_argument("--toxicity-model", help="Add the output toxicity rail")
parser.add_argument("--toxicity-threshold", type=float, default=0.5)
parser.add_argument("--rate-limit", type=int, help="Requests per minute per client")
parser.add_argument("--on-block", choices=["error", "refuse"])
args = parser.parse_args()

with open(args.source) as f:
    policy = yaml.safe_load(f)
if args.injection_threshold is not None:
    policy.setdefault("input_rails", {})["injection"] = {
        "model": args.injection_model,
        "threshold": args.injection_threshold,
        "max_windows": 4,
    }
if args.toxicity_model:
    policy.setdefault("output_rails", {})["toxicity"] = {
        "model": args.toxicity_model,
        "threshold": args.toxicity_threshold,
    }
if args.rate_limit:
    policy["rate_limit"] = {"requests": args.rate_limit, "per_seconds": 60}
if args.on_block:
    policy["on_block"] = args.on_block
with open(args.out, "w") as f:
    f.write(f"# Generated by deploy/make_policy.py from {args.source}.\n")
    yaml.safe_dump(policy, f, sort_keys=False)
